// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ3wCak2RfIS1Js_953bCqQxUStY2MliM',
    appId: '1:1055202103303:web:1762a593196f89486a5aa2',
    messagingSenderId: '1055202103303',
    projectId: 'masemanager-44c9b',
    authDomain: 'masemanager-44c9b.firebaseapp.com',
    storageBucket: 'masemanager-44c9b.firebasestorage.app',
    measurementId: 'G-DNN9PV5SRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcEoJl7_2IfYsfjK71jqrU7cYfCyVEc-g',
    appId: '1:1055202103303:android:3e0aebffc2d760fc6a5aa2',
    messagingSenderId: '1055202103303',
    projectId: 'masemanager-44c9b',
    storageBucket: 'masemanager-44c9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9JMEeZpylV3a2P9HO5cW_Jg4bQlr73c',
    appId: '1:1055202103303:ios:e0a97ce9262a57a06a5aa2',
    messagingSenderId: '1055202103303',
    projectId: 'masemanager-44c9b',
    storageBucket: 'masemanager-44c9b.firebasestorage.app',
    iosBundleId: 'com.example.textApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa9JMEeZpylV3a2P9HO5cW_Jg4bQlr73c',
    appId: '1:1055202103303:ios:e0a97ce9262a57a06a5aa2',
    messagingSenderId: '1055202103303',
    projectId: 'masemanager-44c9b',
    storageBucket: 'masemanager-44c9b.firebasestorage.app',
    iosBundleId: 'com.example.textApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ3wCak2RfIS1Js_953bCqQxUStY2MliM',
    appId: '1:1055202103303:web:dc0273dbd09306266a5aa2',
    messagingSenderId: '1055202103303',
    projectId: 'masemanager-44c9b',
    authDomain: 'masemanager-44c9b.firebaseapp.com',
    storageBucket: 'masemanager-44c9b.firebasestorage.app',
    measurementId: 'G-EPJY7FG8JF',
  );
}
